/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { JwtUser } from "../models/index";
import { JwtUserFromJSON } from "../models/index";
import * as runtime from "../runtime";

/**
 *
 */
export class AdminControllerApi extends runtime.BaseAPI {
	/**
	 */
	async getAdminRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<JwtUser>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration?.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token("bearerAuth", []);

			if (tokenString) {
				headerParameters.Authorization = `Bearer ${tokenString}`;
			}
		}

		const urlPath = `/admin/me`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			JwtUserFromJSON(jsonValue),
		);
	}

	/**
	 */
	async getAdmin(
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<JwtUser> {
		const response = await this.getAdminRaw(initOverrides);
		return await response.value();
	}
}
