/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Assessment,
  CreateAssessmentDTO,
  JwtCandidate,
} from '../models/index';
import {
    AssessmentFromJSON,
    AssessmentToJSON,
    CreateAssessmentDTOFromJSON,
    CreateAssessmentDTOToJSON,
    JwtCandidateFromJSON,
    JwtCandidateToJSON,
} from '../models/index';

export interface CreateAssessmentRequest {
    createAssessmentDTO: CreateAssessmentDTO;
}

export interface CreateJoinTokenRequest {
    sessionId: string;
}

/**
 * 
 */
export class AssessmentControllerApi extends runtime.BaseAPI {

    /**
     */
    async checkCandidateTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JwtCandidate>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/assessment/check-token`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JwtCandidateFromJSON(jsonValue));
    }

    /**
     */
    async checkCandidateToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JwtCandidate> {
        const response = await this.checkCandidateTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async createAssessmentRaw(requestParameters: CreateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['createAssessmentDTO'] == null) {
            throw new runtime.RequiredError(
                'createAssessmentDTO',
                'Required parameter "createAssessmentDTO" was null or undefined when calling createAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/assessment`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAssessmentDTOToJSON(requestParameters['createAssessmentDTO']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createAssessment(requestParameters: CreateAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createJoinTokenRaw(requestParameters: CreateJoinTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling createJoinToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/assessment/join/{sessionId}`;
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createJoinToken(requestParameters: CreateJoinTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createJoinTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllAssessmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assessment>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/assessment`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssessmentFromJSON));
    }

    /**
     */
    async getAllAssessments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assessment>> {
        const response = await this.getAllAssessmentsRaw(initOverrides);
        return await response.value();
    }

}
