/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Assessment
 */
export interface Assessment {
	/**
	 *
	 * @type {number}
	 * @memberof Assessment
	 */
	id?: number;
	/**
	 *
	 * @type {boolean}
	 * @memberof Assessment
	 */
	completed?: boolean;
	/**
	 *
	 * @type {string}
	 * @memberof Assessment
	 */
	candidateName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Assessment
	 */
	candidateEmail?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Assessment
	 */
	inviteNotes?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Assessment
	 */
	adminId?: string;
	/**
	 *
	 * @type {Date}
	 * @memberof Assessment
	 */
	createdAt?: Date;
	/**
	 *
	 * @type {string}
	 * @memberof Assessment
	 */
	code?: string;
	/**
	 *
	 * @type {string}
	 * @memberof Assessment
	 */
	notes?: string;
}

/**
 * Check if a given object implements the Assessment interface.
 */
export function instanceOfAssessment(value: object): value is Assessment {
	return true;
}

export function AssessmentFromJSON(json: any): Assessment {
	return AssessmentFromJSONTyped(json, false);
}

export function AssessmentFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): Assessment {
	if (json == null) {
		return json;
	}
	return {
		id: json["id"] == null ? undefined : json["id"],
		completed: json["completed"] == null ? undefined : json["completed"],
		candidateName:
			json["candidateName"] == null ? undefined : json["candidateName"],
		candidateEmail:
			json["candidateEmail"] == null ? undefined : json["candidateEmail"],
		inviteNotes: json["inviteNotes"] == null ? undefined : json["inviteNotes"],
		adminId: json["adminId"] == null ? undefined : json["adminId"],
		createdAt:
			json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
		code: json["code"] == null ? undefined : json["code"],
		notes: json["notes"] == null ? undefined : json["notes"],
	};
}

export function AssessmentToJSON(json: any): Assessment {
	return AssessmentToJSONTyped(json, false);
}

export function AssessmentToJSONTyped(
	value?: Assessment | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value["id"],
		completed: value["completed"],
		candidateName: value["candidateName"],
		candidateEmail: value["candidateEmail"],
		inviteNotes: value["inviteNotes"],
		adminId: value["adminId"],
		createdAt:
			value["createdAt"] == null
				? value["createdAt"]
				: value["createdAt"].toISOString(),
		code: value["code"],
		notes: value["notes"],
	};
}
