/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAssessmentDTO
 */
export interface CreateAssessmentDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    candidateName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    candidateEmail: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAssessmentDTO
     */
    assessmentNotes: string;
}

/**
 * Check if a given object implements the CreateAssessmentDTO interface.
 */
export function instanceOfCreateAssessmentDTO(value: object): value is CreateAssessmentDTO {
    if (!('candidateName' in value) || value['candidateName'] === undefined) return false;
    if (!('candidateEmail' in value) || value['candidateEmail'] === undefined) return false;
    if (!('assessmentNotes' in value) || value['assessmentNotes'] === undefined) return false;
    return true;
}

export function CreateAssessmentDTOFromJSON(json: any): CreateAssessmentDTO {
    return CreateAssessmentDTOFromJSONTyped(json, false);
}

export function CreateAssessmentDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAssessmentDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'candidateName': json['candidateName'],
        'candidateEmail': json['candidateEmail'],
        'assessmentNotes': json['assessmentNotes'],
    };
}

export function CreateAssessmentDTOToJSON(json: any): CreateAssessmentDTO {
    return CreateAssessmentDTOToJSONTyped(json, false);
}

export function CreateAssessmentDTOToJSONTyped(value?: CreateAssessmentDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidateName': value['candidateName'],
        'candidateEmail': value['candidateEmail'],
        'assessmentNotes': value['assessmentNotes'],
    };
}

