/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateAssessmentRequest
 */
export interface CreateAssessmentRequest {
	/**
	 *
	 * @type {string}
	 * @memberof CreateAssessmentRequest
	 */
	candidateName: string;
	/**
	 *
	 * @type {string}
	 * @memberof CreateAssessmentRequest
	 */
	candidateEmail: string;
	/**
	 *
	 * @type {string}
	 * @memberof CreateAssessmentRequest
	 */
	assessmentNotes: string;
}

/**
 * Check if a given object implements the CreateAssessmentRequest interface.
 */
export function instanceOfCreateAssessmentRequest(
	value: object,
): value is CreateAssessmentRequest {
	if (!("candidateName" in value) || value["candidateName"] === undefined)
		return false;
	if (!("candidateEmail" in value) || value["candidateEmail"] === undefined)
		return false;
	if (!("assessmentNotes" in value) || value["assessmentNotes"] === undefined)
		return false;
	return true;
}

export function CreateAssessmentRequestFromJSON(
	json: any,
): CreateAssessmentRequest {
	return CreateAssessmentRequestFromJSONTyped(json, false);
}

export function CreateAssessmentRequestFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): CreateAssessmentRequest {
	if (json == null) {
		return json;
	}
	return {
		candidateName: json["candidateName"],
		candidateEmail: json["candidateEmail"],
		assessmentNotes: json["assessmentNotes"],
	};
}

export function CreateAssessmentRequestToJSON(
	json: any,
): CreateAssessmentRequest {
	return CreateAssessmentRequestToJSONTyped(json, false);
}

export function CreateAssessmentRequestToJSONTyped(
	value?: CreateAssessmentRequest | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		candidateName: value["candidateName"],
		candidateEmail: value["candidateEmail"],
		assessmentNotes: value["assessmentNotes"],
	};
}
