/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Assessment } from "./Assessment";
import {
	AssessmentFromJSON,
	AssessmentFromJSONTyped,
	AssessmentToJSON,
	AssessmentToJSONTyped,
} from "./Assessment";
import type { WorkspaceEvent } from "./WorkspaceEvent";
import {
	WorkspaceEventFromJSON,
	WorkspaceEventFromJSONTyped,
	WorkspaceEventToJSON,
	WorkspaceEventToJSONTyped,
} from "./WorkspaceEvent";

/**
 *
 * @export
 * @interface EventsResponse
 */
export interface EventsResponse {
	/**
	 *
	 * @type {Array<WorkspaceEvent>}
	 * @memberof EventsResponse
	 */
	events?: Array<WorkspaceEvent>;
	/**
	 *
	 * @type {Assessment}
	 * @memberof EventsResponse
	 */
	assessment?: Assessment;
}

/**
 * Check if a given object implements the EventsResponse interface.
 */
export function instanceOfEventsResponse(
	value: object,
): value is EventsResponse {
	return true;
}

export function EventsResponseFromJSON(json: any): EventsResponse {
	return EventsResponseFromJSONTyped(json, false);
}

export function EventsResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): EventsResponse {
	if (json == null) {
		return json;
	}
	return {
		events:
			json["events"] == null
				? undefined
				: (json["events"] as Array<any>).map(WorkspaceEventFromJSON),
		assessment:
			json["assessment"] == null
				? undefined
				: AssessmentFromJSON(json["assessment"]),
	};
}

export function EventsResponseToJSON(json: any): EventsResponse {
	return EventsResponseToJSONTyped(json, false);
}

export function EventsResponseToJSONTyped(
	value?: EventsResponse | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		events:
			value["events"] == null
				? undefined
				: (value["events"] as Array<any>).map(WorkspaceEventToJSON),
		assessment: AssessmentToJSON(value["assessment"]),
	};
}
