/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User info stored in JWT
 * @export
 * @interface JwtAdmin
 */
export interface JwtAdmin {
    /**
     * User ID
     * @type {string}
     * @memberof JwtAdmin
     */
    userId: string;
    /**
     * Full name of User
     * @type {string}
     * @memberof JwtAdmin
     */
    name: string;
    /**
     * Email of User
     * @type {string}
     * @memberof JwtAdmin
     */
    email: string;
    /**
     * Photo URL of User
     * @type {string}
     * @memberof JwtAdmin
     */
    photoUrl: string;
}

/**
 * Check if a given object implements the JwtAdmin interface.
 */
export function instanceOfJwtAdmin(value: object): value is JwtAdmin {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('photoUrl' in value) || value['photoUrl'] === undefined) return false;
    return true;
}

export function JwtAdminFromJSON(json: any): JwtAdmin {
    return JwtAdminFromJSONTyped(json, false);
}

export function JwtAdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtAdmin {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'email': json['email'],
        'photoUrl': json['photoUrl'],
    };
}

export function JwtAdminToJSON(json: any): JwtAdmin {
    return JwtAdminToJSONTyped(json, false);
}

export function JwtAdminToJSONTyped(value?: JwtAdmin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'email': value['email'],
        'photoUrl': value['photoUrl'],
    };
}

