/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * User info stored in JWT
 * @export
 * @interface JwtUser
 */
export interface JwtUser {
	/**
	 * User ID
	 * @type {string}
	 * @memberof JwtUser
	 */
	userId: string;
	/**
	 * Full name of User
	 * @type {string}
	 * @memberof JwtUser
	 */
	name: string;
	/**
	 * Email of User
	 * @type {string}
	 * @memberof JwtUser
	 */
	email: string;
	/**
	 * Photo URL of User
	 * @type {string}
	 * @memberof JwtUser
	 */
	photoUrl: string;
}

/**
 * Check if a given object implements the JwtUser interface.
 */
export function instanceOfJwtUser(value: object): value is JwtUser {
	if (!("userId" in value) || value["userId"] === undefined) return false;
	if (!("name" in value) || value["name"] === undefined) return false;
	if (!("email" in value) || value["email"] === undefined) return false;
	if (!("photoUrl" in value) || value["photoUrl"] === undefined) return false;
	return true;
}

export function JwtUserFromJSON(json: any): JwtUser {
	return JwtUserFromJSONTyped(json, false);
}

export function JwtUserFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): JwtUser {
	if (json == null) {
		return json;
	}
	return {
		userId: json["userId"],
		name: json["name"],
		email: json["email"],
		photoUrl: json["photoUrl"],
	};
}

export function JwtUserToJSON(json: any): JwtUser {
	return JwtUserToJSONTyped(json, false);
}

export function JwtUserToJSONTyped(
	value?: JwtUser | null,
	ignoreDiscriminator: boolean = false,
): any {
	if (value == null) {
		return value;
	}

	return {
		userId: value["userId"],
		name: value["name"],
		email: value["email"],
		photoUrl: value["photoUrl"],
	};
}
