/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceEvent
 */
export interface WorkspaceEvent {
    /**
     * 
     * @type {number}
     * @memberof WorkspaceEvent
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceEvent
     */
    eventType: WorkspaceEventEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceEvent
     */
    details?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkspaceEvent
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const WorkspaceEventEventTypeEnum = {
    TabSwitch: 'TAB_SWITCH',
    Paste: 'PASTE',
    Copy: 'COPY',
    FocusLost: 'FOCUS_LOST',
    FocusGained: 'FOCUS_GAINED',
    SessionStart: 'SESSION_START',
    SessionEnd: 'SESSION_END',
    CodeRun: 'CODE_RUN',
    CodeChange: 'CODE_CHANGE',
    ExecuteCode: 'EXECUTE_CODE'
} as const;
export type WorkspaceEventEventTypeEnum = typeof WorkspaceEventEventTypeEnum[keyof typeof WorkspaceEventEventTypeEnum];


/**
 * Check if a given object implements the WorkspaceEvent interface.
 */
export function instanceOfWorkspaceEvent(value: object): value is WorkspaceEvent {
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    return true;
}

export function WorkspaceEventFromJSON(json: any): WorkspaceEvent {
    return WorkspaceEventFromJSONTyped(json, false);
}

export function WorkspaceEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'eventType': json['eventType'],
        'details': json['details'] == null ? undefined : json['details'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function WorkspaceEventToJSON(json: any): WorkspaceEvent {
    return WorkspaceEventToJSONTyped(json, false);
}

export function WorkspaceEventToJSONTyped(value?: WorkspaceEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'eventType': value['eventType'],
        'details': value['details'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

