/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthRedirectRouteImport } from './routes/auth/redirect'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAssessmentIdRouteImport } from './routes/admin/assessment/$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth/redirect',
  path: '/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssessmentIdRoute = AdminAssessmentIdRouteImport.update({
  id: '/admin/assessment/$id',
  path: '/admin/assessment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/admin': typeof AdminIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/admin/assessment/$id': typeof AdminAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/admin': typeof AdminIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/admin/assessment/$id': typeof AdminAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/admin/': typeof AdminIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/admin/assessment/$id': typeof AdminAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/test'
    | '/admin/dashboard'
    | '/auth/redirect'
    | '/admin'
    | '/workspace'
    | '/admin/assessment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/test'
    | '/admin/dashboard'
    | '/auth/redirect'
    | '/admin'
    | '/workspace'
    | '/admin/assessment/$id'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/test'
    | '/admin/dashboard'
    | '/auth/redirect'
    | '/admin/'
    | '/workspace/'
    | '/admin/assessment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TestRoute: typeof TestRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  AdminAssessmentIdRoute: typeof AdminAssessmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/auth/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assessment/$id': {
      id: '/admin/assessment/$id'
      path: '/admin/assessment/$id'
      fullPath: '/admin/assessment/$id'
      preLoaderRoute: typeof AdminAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TestRoute: TestRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  AdminIndexRoute: AdminIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  AdminAssessmentIdRoute: AdminAssessmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
