/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Assessment,
  CreateAssessmentRequest,
  EventsResponse,
  JwtCandidate,
} from '../models/index';
import {
    AssessmentFromJSON,
    AssessmentToJSON,
    CreateAssessmentRequestFromJSON,
    CreateAssessmentRequestToJSON,
    EventsResponseFromJSON,
    EventsResponseToJSON,
    JwtCandidateFromJSON,
    JwtCandidateToJSON,
} from '../models/index';

export interface CreateAssessmentOperationRequest {
    createAssessmentRequest: CreateAssessmentRequest;
}

export interface CreateJoinTokenRequest {
    sessionId: string;
}

export interface ReplayRequest {
    sessionId: string;
}

/**
 * 
 */
export class AssessmentControllerApi extends runtime.BaseAPI {

    /**
     */
    async checkCandidateTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JwtCandidate>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/assessment/check-token`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JwtCandidateFromJSON(jsonValue));
    }

    /**
     */
    async checkCandidateToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JwtCandidate> {
        const response = await this.checkCandidateTokenRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async createAssessmentRaw(requestParameters: CreateAssessmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['createAssessmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createAssessmentRequest',
                'Required parameter "createAssessmentRequest" was null or undefined when calling createAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/assessment`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAssessmentRequestToJSON(requestParameters['createAssessmentRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createAssessment(requestParameters: CreateAssessmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createJoinTokenRaw(requestParameters: CreateJoinTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling createJoinToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/assessment/join/{sessionId}`;
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createJoinToken(requestParameters: CreateJoinTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.createJoinTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllAssessmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assessment>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/assessment`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssessmentFromJSON));
    }

    /**
     */
    async getAllAssessments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assessment>> {
        const response = await this.getAllAssessmentsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async replayRaw(requestParameters: ReplayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EventsResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling replay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/assessment/replay/{sessionId}`;
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EventsResponseFromJSON(jsonValue));
    }

    /**
     */
    async replay(requestParameters: ReplayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EventsResponse> {
        const response = await this.replayRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
